;;; cedet

(add-to-list 'load-path "~/github/enviroment/emacs/elisp/cedet-1.1/common")
(require 'cedet)
(require 'semantic-ia)
 
;; Enable EDE (Project Management) features
(global-ede-mode 1)
  
(semantic-load-enable-excessive-code-helpers)
(semantic-load-enable-semantic-debugging-helpers)
   
;; Enable SRecode (Template management) minor-mode.
(global-srecode-minor-mode 1)

;; ecb-activate继续报错Symbol's value as variable is void: stack-trace-on-error 加入(setq stack-trace-on-error t) 恢复正常。
(setq stack-trace-on-error t)
 
;; 使函数体能够折叠或展开
;; Enable source code folding
(global-semantic-tag-folding-mode 1)

(define-key semantic-tag-folding-mode-map (kbd "C-c -") 'semantic-tag-folding-fold-block)
(define-key semantic-tag-folding-mode-map (kbd "C-c =") 'semantic-tag-folding-show-block)
(define-key semantic-tag-folding-mode-map (kbd "C-_") 'semantic-tag-folding-fold-all)
(define-key semantic-tag-folding-mode-map (kbd "C-+") 'semantic-tag-folding-show-all)

;; for gdb debug fringe switch, it will not work when folding mode is on
(global-set-key (kbd "C-?") 'global-semantic-tag-folding-mode)

;; 使能代码补全等功能
(semantic-load-enable-code-helpers)
(semantic-load-enable-semantic-debugging-helpers)

;; 跳转
(global-set-key [(control =)] 'semantic-ia-fast-jump)
(global-set-key [(control -)]
	(lambda ()
		(interactive)
		(if (ring-empty-p (oref semantic-mru-bookmark-ring ring))
		    (error "Semantic Bookmark ring is currently empty"))
		(let* ((ring (oref semantic-mru-bookmark-ring ring))
		       (alist (semantic-mrub-ring-to-assoc-list ring))
		       (first (cdr (car alist))))
	        (if (semantic-equivalent-tag-p (oref first tag)
		    (semantic-current-tag))
		    (setq first (cdr (car (cdr alist)))))
		    (semantic-mrub-switch-tags first))))

(global-set-key [(control \\)] 'semantic-analyze-proto-impl-toggle)

;; 不显示解析不了时的红色下划线
(global-semantic-show-unmatched-syntax-mode 0)

;; gnu global support
(when (cedet-gnu-global-version-check t)
  (require 'semanticdb-global)
  (semanticdb-enable-gnu-global-databases 'c-mode)
  (semanticdb-enable-gnu-global-databases 'c++-mode))

(setq semantic-symref-tool 'global)

;; ctags
(when (cedet-ectag-version-check t)

(require 'semanticdb-ectag)
(semantic-load-enable-primary-exuberent-ctags-support))

;;绑定按键,ctr+tab,以下三种,任意选择一个,我喜欢第二个
;;(global-set-key [(control tab)] 'senator-complete-symbol);
;;(global-set-key [(control tab)] ' senator-completion-menu-popup)
(global-set-key [(control tab)] 'semantic-ia-complete-symbol-menu)
;;**********************        End 自动补全       **********************

;; android common includes for all projects
;; 下面的函数是必须的，因为semantic的大部分功能是autoload的，
;; 如果不在这儿load semantic-c，那打开一个c文件时会自动load semantic-c，
;; 它会把semantic-dependency-system-include-path重设为   
;; /usr/include，结果就造成前面自定义的include路径丢失了。
(require 'semantic-c nil 'noerror)
(semantic-add-system-include "~/android-code/source/abi/cpp/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/bionic/libthread_db/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/bionic/libstdc++/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/bionic/libc/arch-arm/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/bionic/libc/upstream-netbsd/libc/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/bionic/libc/arch-x86/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/bionic/libc/arch-mips/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/bionic/libc/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/bionic/libm/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/iproute2/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/flac/libFLAC/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/flac/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/qemu/distrib/sdl-1.2.15/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/gtest/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/svox/pico/compat/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libvorbis/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/e2fsprogs/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/tinycompress/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/webrtc/src/common_audio/resampler/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/webrtc/src/common_audio/vad/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/webrtc/src/common_audio/signal_processing/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libnfc-nci/halimpl/bcm2079x/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libnfc-nci/src/udrv/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libnfc-nci/src/nfa/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libnfc-nci/src/nfc/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libnfc-nci/src/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libnfc-nci/src/hal/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/freetype/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/tinyalsa/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/antlr/antlr-3.4/runtime/C/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/v8/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libsepol/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/llvm/device/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/llvm/utils/unittest/googletest/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/llvm/host/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/llvm/projects/sample/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/llvm/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/opencv/cvaux/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/opencv/cxcore/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/opencv/ml/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/opencv/cv/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/skia/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium/android/testing/gtest/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium/testing/gtest/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium/testing/gmock/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/ppapi/lib/gl/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/v8/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/native_client_sdk/src/libraries/nacl_io/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/testing/gtest/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/opus/src/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/npapi/npspy/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/freetype/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/jsoncpp/overrides/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/skia/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/mesa/src/src/gtest/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/mesa/src/src/gallium/drivers/svga/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/mesa/src/src/gallium/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/mesa/src/src/gallium/state_trackers/d3d1x/d3d1xshader/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/mesa/src/src/gallium/state_trackers/d3d1x/d3d1xstutil/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/mesa/src/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/leveldatabase/src/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/ots/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/openssl/openssl/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/angle_dx11/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/libxml/mac/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/libxml/win32/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/libxml/src/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/libxml/linux/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/freetype2/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/iptables/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/udrv/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/hci/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/btif/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/utils/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/stack/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/bta/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/embdrv/sbc/encoder/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libffi/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/compiler-rt/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/compiler-rt/SDKs/linux/usr/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/compiler-rt/SDKs/darwin/usr/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/webp/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libogg/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libyuv/files/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/linux-tools-perf/util/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/seti/sltsEngine/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/seti/setiUtils/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/audio/AudioIn/UNIX/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/shared/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/portable/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/Recognizer/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/Grammar/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/Vocabulary/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/Session/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/EventLog/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/AcousticModels/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/Nametag/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/Semproc/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/AcousticState/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/mesa3d/src/gtest/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/mesa3d/src/gallium/drivers/svga/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/mesa3d/src/gallium/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/mesa3d/src/gallium/state_trackers/d3d1x/d3d1xshader/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/mesa3d/src/gallium/state_trackers/d3d1x/d3d1xstutil/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/mesa3d/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/safe-iop/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libvpx/libvpx/vpx_mem/memory_manager/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libvpx/libvpx/vpx_mem/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libvpx/libvpx/nestegg/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libvpx/libvpx/third_party/libyuv/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libvpx/libvpx/third_party/googletest/src/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/speex/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/ceres-solver/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libselinux/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/ppp/pppd/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/libxml2/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libMpegTPDec/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libSBRdec/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libSBRenc/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libAACdec/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libPCMutils/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libMpegTPEnc/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libSYS/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libAACenc/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libFDK/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/protobuf/gtest/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/openssl/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/openfst/src/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/open-vcdiff/gtest/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/PCH/libroot/usr/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Headers/Inputs/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/mips_cs_tree/lib/gcc/mips-linux-gnu/4.6.3/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/mips_cs_tree/mips-linux-gnu/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/mips_cs_tree/mips-linux-gnu/libc/usr/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/hexagon_tree/gnu/lib/gcc/hexagon/4.4.0/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/hexagon_tree/gnu/hexagon/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/debian_multiarch_tree/usr/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/ubuntu_13.04_multiarch_tree/usr/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/ubuntu_11.04_multiarch_tree/usr/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/ubuntu_12.04_LTS_multiarch_tree/usr/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/basic_android_tree/mipsel-linux-android/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/basic_android_tree/arm-linux-androideabi/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Analysis/diagnostics/Inputs/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Modules/Inputs/System/usr/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/lib/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/clang/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srtp/crypto/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/srtp/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/esd/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/valgrind/main/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/external/oprofile/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/libcore/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/packages/inputmethods/OpenWnn/libs/libwnnDictionary/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/packages/inputmethods/PinyinIME/jni/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/developers/build/templates/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/hardware/libhardware/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/hardware/ril/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/hardware/broadcom/wlan/bcmdhd/dhdutil/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/hardware/broadcom/libbt/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/hardware/libhardware_legacy/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/system/security/keystore/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/system/security/softkeymaster/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/system/core/libsparse/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/system/core/logwrapper/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/system/core/fs_mgr/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/system/core/libsuspend/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/system/core/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/system/media/audio_utils/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/system/media/audio_route/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/system/media/camera/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/system/media/audio_effects/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/system/extras/libublock/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/system/extras/libpagemap/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/system/extras/tests/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/compile/mclinker/tools/mcld/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/compile/mclinker/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/compile/libbcc/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/base/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/wilhelm/src/android/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/wilhelm/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/rs/cpu_ref/linkloader/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/codecs/m4v_h263/enc/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/codecs/m4v_h263/dec/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/codecs/amrnb/common/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/codecs/avc/common/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/codecs/common/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/codecs/mp3dec/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/codecs/amrwb/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/drm/libdrmframework/plugins/common/util/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/drm/libdrmframework/plugins/common/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/drm/libdrmframework/plugins/forward-lock/FwdLockEngine/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/drm/libdrmframework/plugins/passthru/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/drm/libdrmframework/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/native/opengl/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/native/opengl/tests/angeles/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/native/opengl/tests/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/frameworks/native/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/libnativehelper/include" 'c++-mode)
(semantic-add-system-include "~/android-code/source/abi/cpp/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/bionic/libthread_db/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/bionic/libstdc++/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/bionic/libc/arch-arm/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/bionic/libc/upstream-netbsd/libc/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/bionic/libc/arch-x86/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/bionic/libc/arch-mips/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/bionic/libc/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/bionic/libm/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/iproute2/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/flac/libFLAC/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/flac/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/qemu/distrib/sdl-1.2.15/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/gtest/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/svox/pico/compat/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libvorbis/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/e2fsprogs/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/tinycompress/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/webrtc/src/common_audio/resampler/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/webrtc/src/common_audio/vad/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/webrtc/src/common_audio/signal_processing/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libnfc-nci/halimpl/bcm2079x/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libnfc-nci/src/udrv/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libnfc-nci/src/nfa/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libnfc-nci/src/nfc/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libnfc-nci/src/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libnfc-nci/src/hal/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/freetype/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/tinyalsa/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/antlr/antlr-3.4/runtime/C/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/v8/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libsepol/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/llvm/device/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/llvm/utils/unittest/googletest/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/llvm/host/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/llvm/projects/sample/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/llvm/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/opencv/cvaux/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/opencv/cxcore/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/opencv/ml/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/opencv/cv/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/skia/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium/android/testing/gtest/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium/testing/gtest/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium/testing/gmock/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/ppapi/lib/gl/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/v8/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/native_client_sdk/src/libraries/nacl_io/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/testing/gtest/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/opus/src/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/npapi/npspy/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/freetype/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/jsoncpp/overrides/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/skia/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/mesa/src/src/gtest/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/mesa/src/src/gallium/drivers/svga/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/mesa/src/src/gallium/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/mesa/src/src/gallium/state_trackers/d3d1x/d3d1xshader/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/mesa/src/src/gallium/state_trackers/d3d1x/d3d1xstutil/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/mesa/src/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/leveldatabase/src/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/ots/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/openssl/openssl/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/angle_dx11/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/libxml/mac/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/libxml/win32/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/libxml/src/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/libxml/linux/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/chromium_org/third_party/freetype2/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/iptables/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/udrv/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/hci/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/btif/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/utils/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/stack/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/bta/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/embdrv/sbc/encoder/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/bluetooth/bluedroid/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libffi/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/compiler-rt/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/compiler-rt/SDKs/linux/usr/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/compiler-rt/SDKs/darwin/usr/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/webp/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libogg/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libyuv/files/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/linux-tools-perf/util/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/seti/sltsEngine/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/seti/setiUtils/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/audio/AudioIn/UNIX/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/shared/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/portable/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/Recognizer/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/Grammar/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/Vocabulary/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/Session/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/EventLog/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/AcousticModels/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/Nametag/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/Semproc/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/AcousticState/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srec/srec/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/mesa3d/src/gtest/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/mesa3d/src/gallium/drivers/svga/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/mesa3d/src/gallium/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/mesa3d/src/gallium/state_trackers/d3d1x/d3d1xshader/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/mesa3d/src/gallium/state_trackers/d3d1x/d3d1xstutil/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/mesa3d/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/safe-iop/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libvpx/libvpx/vpx_mem/memory_manager/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libvpx/libvpx/vpx_mem/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libvpx/libvpx/nestegg/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libvpx/libvpx/third_party/libyuv/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libvpx/libvpx/third_party/googletest/src/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/speex/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/ceres-solver/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libselinux/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/ppp/pppd/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/libxml2/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libMpegTPDec/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libSBRdec/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libSBRenc/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libAACdec/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libPCMutils/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libMpegTPEnc/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libSYS/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libAACenc/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/aac/libFDK/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/protobuf/gtest/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/openssl/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/openfst/src/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/open-vcdiff/gtest/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/PCH/libroot/usr/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Headers/Inputs/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/mips_cs_tree/lib/gcc/mips-linux-gnu/4.6.3/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/mips_cs_tree/mips-linux-gnu/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/mips_cs_tree/mips-linux-gnu/libc/usr/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/hexagon_tree/gnu/lib/gcc/hexagon/4.4.0/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/hexagon_tree/gnu/hexagon/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/debian_multiarch_tree/usr/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/ubuntu_13.04_multiarch_tree/usr/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/ubuntu_11.04_multiarch_tree/usr/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/ubuntu_12.04_LTS_multiarch_tree/usr/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/basic_android_tree/mipsel-linux-android/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Driver/Inputs/basic_android_tree/arm-linux-androideabi/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Analysis/diagnostics/Inputs/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/test/Modules/Inputs/System/usr/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/lib/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/clang/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srtp/crypto/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/srtp/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/esd/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/valgrind/main/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/external/oprofile/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/libcore/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/packages/inputmethods/OpenWnn/libs/libwnnDictionary/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/packages/inputmethods/PinyinIME/jni/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/developers/build/templates/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/hardware/libhardware/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/hardware/ril/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/hardware/broadcom/wlan/bcmdhd/dhdutil/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/hardware/broadcom/libbt/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/hardware/libhardware_legacy/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/system/security/keystore/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/system/security/softkeymaster/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/system/core/libsparse/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/system/core/logwrapper/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/system/core/fs_mgr/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/system/core/libsuspend/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/system/core/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/system/media/audio_utils/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/system/media/audio_route/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/system/media/camera/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/system/media/audio_effects/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/system/extras/libublock/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/system/extras/libpagemap/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/system/extras/tests/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/compile/mclinker/tools/mcld/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/compile/mclinker/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/compile/libbcc/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/base/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/wilhelm/src/android/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/wilhelm/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/rs/cpu_ref/linkloader/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/codecs/m4v_h263/enc/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/codecs/m4v_h263/dec/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/codecs/amrnb/common/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/codecs/avc/common/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/codecs/common/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/codecs/mp3dec/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/codecs/amrwb/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/media/libstagefright/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/drm/libdrmframework/plugins/common/util/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/drm/libdrmframework/plugins/common/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/drm/libdrmframework/plugins/forward-lock/FwdLockEngine/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/drm/libdrmframework/plugins/passthru/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/drm/libdrmframework/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/av/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/native/opengl/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/native/opengl/tests/angeles/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/native/opengl/tests/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/frameworks/native/include" 'c-mode)
(semantic-add-system-include "~/android-code/source/libnativehelper/include" 'c-mode)

